services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nestapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: events
      JWT_SECRET: super-secret-key
      JWT_EXPIRES_IN: 3600s
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
