services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nestapp_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    profiles:
      - dev

  nestapp_prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-management-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    profiles:
      - prod

volumes:
  pgdata:

networks:
  backend:
