services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nestapp_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    profiles:
      - dev

  nestapp_prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    profiles:
      - prod

volumes:
  pgdata:

networks:
  backend:
